In [1]:
import numpy as np

### 1. 创建0维数组（标量）

In [4]:
arr0 = np.array(10, dtype=np.int32)
arr0

array(10, dtype=int32)

### 2. 创建1维数组

In [6]:
arr1 = np.array([1,3,4,5,6,7], dtype=np.float64)
arr1

array([1., 3., 4., 5., 6., 7.])

### 3. 创建2维数组

In [7]:
arr2 = np.array([[1, 2], [3, 4], [5, 6]], dtype=np.uint8)
arr2

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=uint8)

### 4. 创建3维全0布尔数组


In [9]:
arr3 = np.zeros((2, 3, 4), dtype=np.bool_)
arr3

array([[[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]],

       [[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]]])

In [16]:
arr4 = np.ones((2, 3, 4), dtype=np.uint8)
arr4

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=uint8)

### 5.查看每个数组的核心属性：维度（ndim）、形状（shape）、元素总数（size）、数据类型（dtype）。

In [20]:
print("纬度：{}".format(np.ndim(arr4)))
print("形状：{}".format(np.shape(arr4)))
print("元素总数：{}".format(np.size(arr4)))
print("数据类型：{}".format(arr4.dtype))

纬度：3
形状：(2, 3, 4)
元素总数：24
数据类型：uint8


### 6.创建一个 1 维数组，包含 10 个从 0 到 18 的偶数

In [25]:
arr6 = np.arange(0, 19, 2)
arr6

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### 7.创建一个 2 维数组（4 行 4 列），对角线为 1，其余为 0（单位矩阵）；

In [31]:
# arr7 = np.zeros((4, 4), dtype=np.uint8)
arr7 = np.eye(4, dtype=np.int32)
arr7

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

### 8.创建一个 3 维数组（2×2×2），元素为 0 到 7 的随机整数（0≤x<8）；

In [34]:
np.random.seed(43)
arr8 = np.random.randint(0, 8, size=(2, 2, 2))
arr8

array([[[4, 0],
        [7, 1]],

       [[5, 2],
        [0, 3]]])

### 9.将上述偶数数组的数据类型从默认的 int64 转换为 int16；

In [39]:
arr9 = np.arange(0, 19, 2)
print(arr9, arr9.dtype)
arr9_1 = arr9.astype(np.int16)
print(arr9_1, arr9_1.dtype)

[ 0  2  4  6  8 10 12 14 16 18] int64
[ 0  2  4  6  8 10 12 14 16 18] int16


### 10.数组索引与切片
题目要求
给定 2 维数组arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])，完成以下操作：
取出第 2 行（索引从 0 开始）的所有元素；
取出所有行的第 3 列元素；
取出第 1-3 行（包含）、第 2-4 列（包含）的子数组；
取出数组中所有大于 8 的元素，返回 1 维数组；
用花式索引取出第 0 行和第 3 行、第 1 列和第 3 列的元素，形成 2×2 数组。

In [48]:
arr10 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(arr10)
arr10[2, :]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([ 9, 10, 11, 12])

In [45]:
arr10[:, 3]

array([ 4,  8, 12, 16])

In [49]:
arr10[1:4, 0:4]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [50]:
arr10[arr10 > 8]

array([ 9, 10, 11, 12, 13, 14, 15, 16])

In [51]:
arr10[[0, 3], :][:, [1, 3]]

array([[ 2,  4],
       [14, 16]])

### 11.形状变换与拼接拆分
题目要求
将 1 维数组arr = np.arange(12)转换为 3 行 4 列的 2 维数组；
将上述 2 维数组转置（行变列、列变行）；
将两个 2 维数组arr1 = np.ones((2,3))和arr2 = np.zeros((2,3))按行拼接（垂直拼接）；
将拼接后的数组按列拆分为 3 个相等的子数组；
将 1 维数组arr = np.arange(6)重塑为 3×2 数组，并展平为 1 维数组（两种方式）。

In [64]:
# 1. 形状变换
arr11 = np.arange(12)
arr11_3x4 = arr11.reshape(3, 4)
arr11_3x4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [59]:
# 2. 转置
arr11_trans = arr11_3x4.T
arr11_trans

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [65]:
# 3. 垂直拼接（行方向）
arr11_1 = np.ones((2, 3))
arr11_2 = np.zeros((2, 3))
arr11_concat1 = np.vstack((arr11_1, arr11_2))
print(arr11_concat1)
arr11_concat2 = np.stack((arr11_1, arr11_2))
arr11_concat2

[[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [75]:
# 4. 按列拆分
arr11_split = np.hsplit(arr11_concat1, 3)
print(arr11_split)
for i, sub in enumerate(arr11_split):
    print(f"子数组{i+1}:\n", sub)

[array([[1.],
       [1.],
       [0.],
       [0.]]), array([[1.],
       [1.],
       [0.],
       [0.]]), array([[1.],
       [1.],
       [0.],
       [0.]])]
子数组1:
 [[1.]
 [1.]
 [0.]
 [0.]]
子数组2:
 [[1.]
 [1.]
 [0.]
 [0.]]
子数组3:
 [[1.]
 [1.]
 [0.]
 [0.]]


In [80]:
# 1 维数组arr = np.arange(6)重塑为 3×2 数组，并展平为 1 维数组（两种方式）。
arr11_6 = np.arange(6)
arr11_6.reshape(3, 2)
print(arr11_6)
arr11_6_ravel = arr11_6.ravel() # 返回视图，修改会影响原数组（更高效）
arr11_6_ravel[0] = 100
arr11_6_flatten = arr11_6.flatten() # 返回副本，修改不影响原数组
arr11_6_flatten[0] = 101
print(arr11_6_ravel)
print(arr11_6_flatten)
arr11_6

[0 1 2 3 4 5]
[100   1   2   3   4   5]
[101   1   2   3   4   5]


array([100,   1,   2,   3,   4,   5])

### 12.数值计算与统计分析（核心：元素级运算、统计函数）
核心目标
掌握 NumPy 的元素级运算（替代循环）、统计函数（均值 / 方差 / 分位数）、条件筛选与替换。
练习题 1：元素级运算与广播基础
题目要求
给定两个 1 维数组a = np.array([1,2,3])和b = np.array([4,5,6])，计算：
元素级加法、减法、乘法、除法；
数组 a 的平方、数组 b 的平方根；
两个数组的点积（内积）。
将数组a与标量 10 进行加法运算（验证广播）；
将 2 维数组arr = np.array([[1,2],[3,4]])与 1 维数组[10,20]进行乘法运算（验证广播）。

In [87]:
# 元素级加法、减法、乘法、除法  数组 a 的平方、数组 b 的平方根； 两个数组的点积（内积）
a = np.array([1,2,3])
b = np.array([4,5,6])
add = a + b
sub = a - b
mul = a * b
div = a / b
square_a = a ** 2
sqrt_b = np.sqrt(b)
dot_product = np.dot(a, b)
a_plus_10 = a + 10
arr = np.array([[1,2],[3,4]])
arr_mul = arr * np.array([10, 20])
print(add, sub, mul, div, square_a, sqrt_b, dot_product, a_plus_10, arr_mul)

[5 7 9] [-3 -3 -3] [ 4 10 18] [0.25 0.4  0.5 ] [1 4 9] [2.         2.23606798 2.44948974] 32 [11 12 13] [[10 40]
 [30 80]]


### 13.统计函数与条件操作
题目要求
给定数组arr = np.random.randn(5, 4)（5 行 4 列的正态分布随机数），完成：
计算数组的全局均值、每行均值、每列均值；
计算数组的最大值、最小值、标准差、方差；
找出数组中最大值的位置（索引）；
将数组中小于 0 的元素替换为 0，大于 2 的元素替换为 2；
计算数组中大于 0 的元素的个数。

In [109]:
arr = np.random.randn(5, 4)
print(arr)
mean_global = arr.mean()
mean_row = arr.mean(axis=1)
mean_col = arr.mean(axis=0)
#print(arr, mean_global, mean_row, mean_col)

arr_max = arr.max()
arr_min = arr.min()
arr_std = arr.std()
arr_var = arr.var()
print(arr_max, arr_min, arr_std, arr_var)

[[-2.0176859   0.72519311 -2.02724386  0.33697833]
 [-0.04469832  0.29207407 -0.6484989   1.69347825]
 [ 0.71809248  0.63541617 -0.17893561 -0.07525435]
 [ 0.88569809  1.30229072  1.40017513 -0.0463873 ]
 [ 0.05670135  0.33108022 -0.26178089 -0.70926492]]
1.6934782478194783 -2.027243860485218 0.9486910337942053 0.9000146776015179


In [116]:
# arr.argmax()
max_idx = np.unravel_index(arr.argmax(), arr.shape)
# arr[max_idx[0], max_idx[1]]
max_idx

(1, 3)

In [122]:
#arr[arr<0] = 0
arr_clipped = np.clip(arr, 0, 2)  # 小于0→0，大于2→2
# 等价写法：arr[(arr<0)]=0; arr[(arr>2)]=2
print("\n4. 裁剪后的数组:\n", arr_clipped)
count_gt0 = np.sum(arr > 0)
count_gt0


4. 裁剪后的数组:
 [[0.         0.72519311 0.         0.33697833]
 [0.         0.29207407 0.         1.69347825]
 [0.71809248 0.63541617 0.         0.        ]
 [0.88569809 1.30229072 1.40017513 0.        ]
 [0.05670135 0.33108022 0.         0.        ]]


11

### 14.广播机制与向量化（核心：广播规则、替代循环）
核心目标
理解广播的核心规则，掌握用向量化操作替代 Python 循环（提升性能）。
练习题 1：广播规则验证
题目要求
验证以下维度组合是否满足广播规则，若满足则输出结果维度：
(3,4) 和 (4,) → 满足，结果 (3,4)
(2,3,4) 和 (3,4) → 满足，结果 (2,3,4)
(2,3) 和 (3,2) → 不满足
(5,1,6) 和 (4,6) → 满足，结果 (5,4,6)
手动实现广播：将数组arr1 = np.array([[1],[2],[3]])（3×1）与arr2 = np.array([4,5,6])（1×3）相加，验证结果维度为 3×3。


In [146]:
def check_broadcast(shape1, shape2):
    try: 
        a = np.ones(shape1)
        b = np.ones(shape2)
        res = a + b
        return f"满足广播规则，结果纬度：{res.shape}"
    except ValueError as e:
        return f"不满足广播规则，错误：{e}"
    
cases = [
    ((3,4), (4,)),
    ((2,3,4), (3,4)),
    ((2,3), (3,2)),
    ((5,1,6), (4,6))
]

print("1. 广播规则验证:")
for i, (s1, s2) in enumerate(cases):
    print(f"案例{i+1}: {s1} 和 {s2} → {check_broadcast(s1, s2)}")

1. 广播规则验证:
案例1: (3, 4) 和 (4,) → 满足广播规则，结果纬度：(3, 4)
案例2: (2, 3, 4) 和 (3, 4) → 满足广播规则，结果纬度：(2, 3, 4)
案例3: (2, 3) 和 (3, 2) → 不满足广播规则，错误：operands could not be broadcast together with shapes (2,3) (3,2) 
案例4: (5, 1, 6) 和 (4, 6) → 满足广播规则，结果纬度：(5, 4, 6)


In [130]:
arr1 = np.array([[1],[2],[3]])
arr2 = np.array([4,5,6])
arr3 = arr1 + arr2
print(arr3.shape)
arr3

(3, 3)


array([[5, 6, 7],
       [6, 7, 8],
       [7, 8, 9]])

### 15.向量化替代循环（性能优化）
题目要求
用 Python 循环实现：计算数组arr = np.arange(1000000)中每个元素的平方；
用 NumPy 向量化操作实现相同功能；
对比两种方式的执行时间，验证向量化的性能优势；
进阶：用向量化实现 “计算两个数组对应元素的欧式距离”（避免双重循环）。

In [147]:
arr = np.arange(1000000)
import time
start = time.time()
result_loop = np.zeros_like(arr, dtype=np.int64)
for idx, num in enumerate(arr): 
    result_loop[idx] = num ** 2
end = time.time()
time_loop = end - start
print(f"执行时间：{time_loop:.6f}秒")

执行时间：0.301178秒


In [138]:
arr = np.arange(1000000)
import time
start = time.time()
arr = arr ** 2
end = time.time()
time_loop = end - start
print(f"执行时间：{time_loop:.6f}秒")

执行时间：0.002428秒


In [145]:
# 3. 向量化计算欧式距离
np.random.seed(42)
a = np.random.rand(1000, 3)  # 1000个3维点
b = np.random.rand(1000, 3)  # 1000个3维点

# 循环实现（双重循环）
start = time.time()
dist_loop = np.zeros(1000)
for i in range(1000):
    dist = 0
    for j in range(3):
        dist += (a[i,j] - b[i,j])**2
    dist_loop[i] = np.sqrt(dist)
time_loop_dist = time.time() - start

# 向量化实现
start = time.time()
dist_vec = np.sqrt(np.sum((a - b)** 2, axis=1))
time_vec_dist = time.time() - start

print(f"\n3. 欧式距离 - 循环时间: {time_loop_dist:.6f} 秒")
print(f"   欧式距离 - 向量化时间: {time_vec_dist:.6f} 秒")
print(f"   距离计算性能提升: {time_loop_dist/time_vec_dist:.2f} 倍")


3. 欧式距离 - 循环时间: 0.005335 秒
   欧式距离 - 向量化时间: 0.007239 秒
   距离计算性能提升: 0.74 倍


### 16.线性代数与矩阵运算（核心：矩阵乘法、逆矩阵、特征值）
核心目标
掌握 NumPy 线性代数模块（np.linalg）的常用功能，适配机器学习 / 数据分析中的矩阵运算场景。
练习题 1：基础矩阵运算
题目要求
创建两个矩阵A = np.array([[1,2],[3,4]])和B = np.array([[5,6],[7,8]])，计算：
矩阵乘法（A・B）；
矩阵的行列式（det (A)）；
矩阵 A 的逆矩阵（A⁻¹）；
验证 A・A⁻¹ = 单位矩阵（忽略浮点误差）；
解线性方程组：
{ 
2x+3y=8
5x−y=3
​

In [150]:
import numpy as np

# 1. 矩阵运算
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

# 矩阵乘法（注意：*是元素级，@是矩阵乘法）
mat_mul = A @ B  # 等价于np.matmul(A, B)
print(A)
print(B)
print("1. 矩阵乘法 A·B:\n", mat_mul)

# 行列式
det_A = np.linalg.det(A)
print("\n矩阵A的行列式:", det_A)

# 逆矩阵
inv_A = np.linalg.inv(A)
print("\n矩阵A的逆矩阵:\n", inv_A)

# 验证A·A⁻¹ = 单位矩阵
identity = A @ inv_A
print("\nA·A⁻¹（近似单位矩阵）:\n", np.round(identity, 0))  # 四舍五入消除浮点误差

# 2. 解线性方程组 Ax = b
# 方程组：2x+3y=8, 5x-y=3 → A=[[2,3],[5,-1]], b=[8,3]
A_eq = np.array([[2,3],[5,-1]])
b_eq = np.array([8,3])
x = np.linalg.solve(A_eq, b_eq)
print("\n2. 线性方程组解 (x,y):", x)
# 验证
print("验证: 2x+3y =", 2*x[0] + 3*x[1])
print("验证: 5x-y =", 5*x[0] - x[1])

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
1. 矩阵乘法 A·B:
 [[19 22]
 [43 50]]

矩阵A的行列式: -2.0000000000000004

矩阵A的逆矩阵:
 [[-2.   1. ]
 [ 1.5 -0.5]]

A·A⁻¹（近似单位矩阵）:
 [[1. 0.]
 [0. 1.]]

2. 线性方程组解 (x,y): [1. 2.]
验证: 2x+3y = 8.0
验证: 5x-y = 3.0


### 17.特征值与矩阵分解
题目要求
计算对称矩阵arr = np.array([[4,2],[2,4]])的特征值和特征向量；
对矩阵arr = np.random.rand(3,3)进行奇异值分解（SVD）；
计算矩阵的秩、迹（对角线元素和）。

In [141]:
import numpy as np

np.random.seed(42)

# 1. 特征值与特征向量
arr_sym = np.array([[4,2],[2,4]])
eigenvals, eigenvecs = np.linalg.eig(arr_sym)
print("1. 特征值:", eigenvals)
print("特征向量（每列是一个特征向量）:\n", eigenvecs)

# 验证：A·v = λ·v
v = eigenvecs[:, 0]  # 第一个特征向量
lambda_v = eigenvals[0]  # 第一个特征值
print("\n验证 A·v = λ·v:")
print("A·v =", arr_sym @ v)
print("λ·v =", lambda_v * v)

# 2. 奇异值分解（SVD）
arr_rand = np.random.rand(3,3)
U, S, VT = np.linalg.svd(arr_rand)
print("\n2. SVD分解结果:")
print("U矩阵（左奇异向量）:\n", np.round(U, 2))
print("奇异值S:", np.round(S, 2))
print("VT矩阵（右奇异向量转置）:\n", np.round(VT, 2))

# 3. 秩和迹
rank = np.linalg.matrix_rank(arr_rand)
trace = np.trace(arr_rand)
print("\n3. 矩阵秩:", rank)
print("矩阵迹:", trace)

1. 特征值: [6. 2.]
特征向量（每列是一个特征向量）:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]

验证 A·v = λ·v:
A·v = [4.24264069 4.24264069]
λ·v = [4.24264069 4.24264069]

2. SVD分解结果:
U矩阵（左奇异向量）:
 [[-0.75 -0.06 -0.65]
 [-0.22 -0.91  0.35]
 [-0.62  0.41  0.67]]
奇异值S: [1.67 0.57 0.03]
VT矩阵（右奇异向量转置）:
 [[-0.27 -0.77 -0.57]
 [-0.96  0.26  0.1 ]
 [ 0.08  0.58 -0.81]]

3. 矩阵秩: 3
矩阵迹: 1.1316737710330078


### 18.高级技巧与性能优化（核心：花式索引、ufunc、内存优化）
核心目标
掌握 NumPy 的高级用法，解决实际场景中的性能和内存问题。
练习题 1：花式索引与条件筛选进阶
题目要求
从数组arr = np.random.randint(0, 100, (10, 10))中：
取出所有偶数行、奇数列的元素；
取出前 5 行中大于 50 的元素，并按降序排序；
将数组中第 3 行的元素替换为该行元素的均值；
用np.where()实现：将数组中小于 30 的元素设为 0，大于等于 30 的设为原值。

In [143]:
import numpy as np

np.random.seed(42)
arr = np.random.randint(0, 100, (10, 10))
print("原始数组:\n", arr)

# 1. 花式索引
# 偶数行（0,2,4,6,8）、奇数列（1,3,5,7,9）
even_rows_odd_cols = arr[::2, 1::2]  # ::2是步长2（偶数行），1::2是从1开始步长2（奇数列）
print("\n1. 偶数行、奇数列元素:\n", even_rows_odd_cols)

# 前5行中大于50的元素，降序排序
top5_gt50 = arr[:5][arr[:5] > 50]
top5_gt50_sorted = np.sort(top5_gt50)[::-1]  # 排序后反转（降序）
print("\n前5行大于50的元素（降序）:", top5_gt50_sorted)

# 替换第3行为该行均值
arr[3] = arr[3].mean()
print("\n替换第3行后的数组:\n", arr)

# 2. np.where()条件替换
arr_where = np.where(arr < 30, 0, arr)
print("\n2. np.where替换后（<30→0）:\n", arr_where)

原始数组:
 [[51 92 14 71 60 20 82 86 74 74]
 [87 99 23  2 21 52  1 87 29 37]
 [ 1 63 59 20 32 75 57 21 88 48]
 [90 58 41 91 59 79 14 61 61 46]
 [61 50 54 63  2 50  6 20 72 38]
 [17  3 88 59 13  8 89 52  1 83]
 [91 59 70 43  7 46 34 77 80 35]
 [49  3  1  5 53  3 53 92 62 17]
 [89 43 33 73 61 99 13 94 47 14]
 [71 77 86 61 39 84 79 81 52 23]]

1. 偶数行、奇数列元素:
 [[92 71 20 86 74]
 [63 20 75 21 48]
 [50 63 50 20 38]
 [59 43 46 77 35]
 [43 73 99 94 14]]

前5行大于50的元素（降序）: [99 92 91 90 88 87 87 86 82 79 75 74 74 72 71 63 63 61 61 61 60 59 59 58
 57 54 52 51]

替换第3行后的数组:
 [[51 92 14 71 60 20 82 86 74 74]
 [87 99 23  2 21 52  1 87 29 37]
 [ 1 63 59 20 32 75 57 21 88 48]
 [60 60 60 60 60 60 60 60 60 60]
 [61 50 54 63  2 50  6 20 72 38]
 [17  3 88 59 13  8 89 52  1 83]
 [91 59 70 43  7 46 34 77 80 35]
 [49  3  1  5 53  3 53 92 62 17]
 [89 43 33 73 61 99 13 94 47 14]
 [71 77 86 61 39 84 79 81 52 23]]

2. np.where替换后（<30→0）:
 [[51 92  0 71 60  0 82 86 74 74]
 [87 99  0  0  0 52  0 87  0 37]
 [ 0 63 59  0 32

### 19.性能优化与内存管理
题目要求
对比np.ufunc（通用函数）与 Python 循环的性能：计算数组arr = np.arange(1e6)的正弦值；
用np.memmap创建内存映射数组（处理大文件，避免加载全部数据到内存）；
将数组arr = np.random.rand(1000, 1000)转换为更节省内存的float32类型，计算内存占用变化。

In [144]:
import numpy as np
import time
import os

# 1. ufunc vs 循环（计算正弦值）
arr = np.arange(1000000, dtype=np.float64)

# Python循环
start = time.time()
sin_loop = np.zeros_like(arr)
for i in range(len(arr)):
    sin_loop[i] = np.sin(arr[i])
time_loop = time.time() - start

# NumPy ufunc（向量化）
start = time.time()
sin_ufunc = np.sin(arr)
time_ufunc = time.time() - start

print(f"1. 循环计算正弦值时间: {time_loop:.6f} 秒")
print(f"   ufunc计算正弦值时间: {time_ufunc:.6f} 秒")
print(f"   性能提升: {time_loop/time_ufunc:.2f} 倍")

# 2. 内存映射数组（处理大文件）
# 创建大数组并保存到文件
big_arr = np.random.rand(10000, 10000).astype(np.float32)
np.save("big_arr.npy", big_arr)
print(f"\n2. 大数组文件大小: {os.path.getsize('big_arr.npy')/1024/1024:.2f} MB")

# 用memmap加载（仅映射，不加载全部数据）
memmap_arr = np.load("big_arr.npy", mmap_mode="r")
print("内存映射数组形状:", memmap_arr.shape)
print("内存映射数组前2×2元素:\n", memmap_arr[:2, :2])

# 3. 内存优化（float64 → float32）
arr = np.random.rand(1000, 1000)  # 默认float64
mem_64 = arr.nbytes / 1024 / 1024  # 转MB
arr_32 = arr.astype(np.float32)
mem_32 = arr_32.nbytes / 1024 / 1024

print(f"\n3. float64内存占用: {mem_64:.2f} MB")
print(f"   float32内存占用: {mem_32:.2f} MB")
print(f"   内存节省比例: {1 - mem_32/mem_64:.2f}")

# 清理文件
os.remove("big_arr.npy")

1. 循环计算正弦值时间: 0.933705 秒
   ufunc计算正弦值时间: 0.012905 秒
   性能提升: 72.35 倍

2. 大数组文件大小: 381.47 MB
内存映射数组形状: (10000, 10000)
内存映射数组前2×2元素:
 [[0.35675332 0.2809345 ]
 [0.22996141 0.14813392]]

3. float64内存占用: 7.63 MB
   float32内存占用: 3.81 MB
   内存节省比例: 0.50
